spring:
  application:
    name: skeleton
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/skeleton
    username: skeleton
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
  api-docs:
    path: /api-docs
logging:
  level:
    org:
      springframework:
        cache: DEBUG